apiVersion: v1
kind: Secret
metadata:
  name: kafkadash-secrets
  namespace: default
  labels:
    app: kafkadash
    version: v1.0.0
type: Opaque
data:
  # Kafka broker configuration (base64 encoded)
  # Update this value with your actual Kafka brokers
  # Example: echo -n "kafka-broker-1:9092,kafka-broker-2:9092" | base64
  KAFKA_BROKERS: a2Fma2EtYnJva2VyLTE6OTA5Mma2Fma2EtYnJva2VyLTI6OTA5Mg==  # kafka-broker-1:9092,kafka-broker-2:9092
  
  # Optional: Add authentication secrets if Kafka requires SASL/SSL
  # KAFKA_USERNAME: <base64-encoded-username>
  # KAFKA_PASSWORD: <base64-encoded-password>
  # KAFKA_SASL_MECHANISM: <base64-encoded-mechanism> # e.g., PLAIN, SCRAM-SHA-256
  
  # Optional: SSL configuration if Kafka uses SSL
  # KAFKA_SSL_CA: <base64-encoded-ca-certificate>
  # KAFKA_SSL_CERT: <base64-encoded-client-certificate>
  # KAFKA_SSL_KEY: <base64-encoded-client-key>

---
# To generate base64 encoded values, use:
# echo -n "your-value-here" | base64
#
# Common configurations:
# For local development:
# echo -n "localhost:9092" | base64
# Result: bG9jYWxob3N0OjkwOTI=
#
# For multiple brokers:
# echo -n "kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092" | base64
